apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
        containers:
        - name: hello-app
          image: anishka012/hello_app:latest
          ports:
          - containerPort: 80

          readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10   # Adjusted periodSeconds
          timeoutSeconds: 5   # Adjusted timeoutSeconds
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15   # Adjusted periodSeconds
          timeoutSeconds: 8    # Adjusted timeoutSeconds
