apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: anishka012/hello_app:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz   
            port: 80
          periodSeconds: 15  
          timeoutSeconds: 5   
        readinessProbe:
          httpGet:
            path: /readiness   
            port: 80
          periodSeconds: 10    
          timeoutSeconds: 3     
