name: Terraform Destroy

on:
  workflow_dispatch
jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.9

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: |
        cd ${{ env.TERRAFORM_CLI_PATH }}
        terraform destroy -auto-approve
